logging:
  level:
    root: trace
server:
  port: 8081
spring:
  application:
    name: spotify-mcp-server
  config:
    import: optional:file:.env[.properties]
  #  main:
  #    web-application-type: none
  #    banner-mode: off
  ai:
    mcp:
      server:
        name: spotify-mcp-server
        version: 1.0.0
        type: SYNC
        #        stdio: true
        enabled: true
        sse-message-endpoint: /mcp/messages
        sse-endpoint: /sse
spotify:
  api:
    token: ${SPOTIFY_API_TOKEN}
